name = "valaig"
version = "0.1.0"
defaultTargets = ["valaig", "valaigmiloabcjf", "Valaig"]

[[lean_lib]]
name = "Valaig"

[[lean_exe]]
name = "valaig"
root = "Main"

[[lean_exe]]
name = "valaigmiloabcjf"
root = "Valaig.Tools.ValaigMILOABCJF"
