name = "valaig"
version = "0.1.0"
defaultTargets = ["valaig"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "nightly-testing-2026-02-01"

[[lean_lib]]
name = "Valaig"

[[lean_exe]]
name = "valaig"
root = "Main"
