name = "valaig"
version = "0.1.0"
defaultTargets = ["valaigcert", "valaigmiloabcjf", "Valaig"]

[[lean_lib]]
name = "Valaig"

[[lean_exe]]
name = "valaigcert"
root = "Tools.ValaigCert"

[[lean_exe]]
name = "valaigmiloabcjf"
root = "Tools.ValaigMILOABCJF"
